import { Category, Product, TaxRule, DiscountPromotion, User } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat_frutas_verduras',
    name: 'Frutas y Verduras',
    slug: 'frutas-verduras',
    description: 'Productos frescos del campo directamente a tu mesa',
    iconName: 'Apple',
    color: 'emerald',
    bannerUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat_lacteos_huevos',
    name: 'Lácteos y Huevos',
    slug: 'lacteos-huevos',
    description: 'Leches, quesos maduros, yogures artesanales y huevos frescos',
    iconName: 'Milk',
    color: 'blue',
    bannerUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat_carnes_pescados',
    name: 'Carnes y Aves',
    slug: 'carnes-aves',
    description: 'Cortes premium seleccionados, res, pollo y cerdo de primera',
    iconName: 'Beef',
    color: 'red',
    bannerUrl: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat_panaderia',
    name: 'Panadería y Café',
    slug: 'panaderia-cafe',
    description: 'Panes recién horneados, café de origen y repostería fina',
    iconName: 'Croissant',
    color: 'amber',
    bannerUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat_despensa',
    name: 'Despensa y Granos',
    slug: 'despensa-granos',
    description: 'Arroz, aceites de oliva, pastas, cereales y conservas',
    iconName: 'Package',
    color: 'orange',
    bannerUrl: 'https://images.unsplash.com/photo-1588964895597-cfccd6e2dbf9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat_bebidas',
    name: 'Bebidas y Jugos',
    slug: 'bebidas-jugos',
    description: 'Jugos 100% naturales, aguas purificadas, refrescos e infusiones',
    iconName: 'CupSoda',
    color: 'cyan',
    bannerUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat_aseo_hogar',
    name: 'Aseo y Cuidado del Hogar',
    slug: 'aseo-hogar',
    description: 'Detergentes biodegradables, desinfectantes y cuidado personal',
    iconName: 'Sparkles',
    color: 'indigo',
    bannerUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat_snacks',
    name: 'Snacks y Dulces',
    slug: 'snacks-dulces',
    description: 'Frutos secos, chocolates artesanales, galletas y botanas',
    iconName: 'Cookie',
    color: 'purple',
    bannerUrl: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&w=800&q=80',
  }
];

export const INITIAL_TAX_RULES: TaxRule[] = [
  {
    id: 'tax_iva_general',
    name: 'IVA General (19%)',
    rate: 0.19,
    description: 'Impuesto al valor agregado estándar aplicable a la mayoría de bienes procesados y aseo.',
    isDefault: true,
    isActive: true,
  },
  {
    id: 'tax_iva_reducido',
    name: 'IVA Reducido (5%)',
    rate: 0.05,
    description: 'Tarifa preferencial para alimentos básicos procesados y harinas.',
    isDefault: false,
    isActive: true,
  },
  {
    id: 'tax_exento',
    name: 'Exento de IVA (0%)',
    rate: 0.0,
    description: 'Productos de la canasta básica familiar no gravados (frutas frescas, verduras, carnes crudas, huevos).',
    isDefault: false,
    isActive: true,
  }
];

export const INITIAL_DISCOUNTS: DiscountPromotion[] = [
  {
    id: 'promo_d2_bienvenida',
    code: 'D2BIENVENIDA',
    title: 'Descuento de Bienvenida D2',
    description: '10% de descuento en tu primera compra en compras superiores a $30.000',
    discountType: 'percentage',
    value: 10,
    minSpend: 30000,
    maxDiscount: 25000,
    isActive: true,
    validUntil: '2026-12-31',
  },
  {
    id: 'promo_superd2',
    code: 'SUPERD2',
    title: 'Super Ahorro D2',
    description: '15% de descuento en pedidos mayores a $80.000',
    discountType: 'percentage',
    value: 15,
    minSpend: 80000,
    maxDiscount: 40000,
    isActive: true,
    validUntil: '2026-12-31',
  },
  {
    id: 'promo_frescos15',
    code: 'FRESCOS15',
    title: 'Especial Frescura del Campo',
    description: '15% en Frutas y Verduras en compras superiores a $20.000',
    discountType: 'percentage',
    value: 15,
    minSpend: 20000,
    categoryId: 'cat_frutas_verduras',
    isActive: true,
    validUntil: '2026-12-31',
  },
  {
    id: 'promo_ahorro5k',
    code: 'AHORRO5K',
    title: 'Bono Directo $5.000',
    description: '$5.000 de descuento directo en cualquier compra mayor a $45.000',
    discountType: 'fixed',
    value: 5000,
    minSpend: 45000,
    isActive: true,
    validUntil: '2026-12-31',
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  // Frutas y Verduras (Exento de IVA)
  {
    id: 'prod_manzana_royal',
    name: 'Manzana Royal Gala Importada',
    description: 'Manzanas frescas, crujientes y dulces. Ideales para meriendas y repostería saludable.',
    price: 6500,
    originalPrice: 7800,
    categoryId: 'cat_frutas_verduras',
    stock: 45,
    unit: 'Bolsa 1kg',
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80',
    isFeatured: true,
    barcode: '770123456001',
    brand: 'D2 Selección',
    taxRateId: 'tax_exento',
  },
  {
    id: 'prod_aguacate_hass',
    name: 'Aguacate Hass Premium',
    description: 'Aguacates cremosos en su punto perfecto de maduración. Ricos en grasas saludables.',
    price: 8900,
    categoryId: 'cat_frutas_verduras',
    stock: 60,
    unit: 'Malla 3 unid.',
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=600&q=80',
    isFeatured: true,
    barcode: '770123456002',
    brand: 'D2 Frescos',
    taxRateId: 'tax_exento',
  },
  {
    id: 'prod_platano_maduro',
    name: 'Plátano Hartón Maduro',
    description: 'Plátano dulce listo para freír, hornear o asar.',
    price: 4200,
    categoryId: 'cat_frutas_verduras',
    stock: 75,
    unit: 'Mano 4 unid.',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
    isFeatured: false,
    barcode: '770123456003',
    brand: 'D2 Frescos',
    taxRateId: 'tax_exento',
  },
  {
    id: 'prod_tomate_chonto',
    name: 'Tomate Chonto de Primera',
    description: 'Tomates rojos, firmes y carnosos para ensaladas y guisos.',
    price: 3800,
    originalPrice: 4500,
    categoryId: 'cat_frutas_verduras',
    stock: 90,
    unit: 'Bolsa 1kg',
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
    isFeatured: false,
    barcode: '770123456004',
    brand: 'D2 Frescos',
    taxRateId: 'tax_exento',
  },

  // Lácteos y Huevos
  {
    id: 'prod_leche_entera',
    name: 'Leche Entera Larga Vida Pack x6',
    description: 'Leche entera pasteurizada enriquecida con vitaminas A y D.',
    price: 24500,
    originalPrice: 27900,
    categoryId: 'cat_lacteos_huevos',
    stock: 35,
    unit: 'Pack 6 x 1L',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80',
    isFeatured: true,
    barcode: '770123456005',
    brand: 'Alquería',
    taxRateId: 'tax_exento',
  },
  {
    id: 'prod_queso_mozzarella',
    name: 'Queso Mozzarella Tajado',
    description: 'Queso hilado perfecto para sándwiches, lasagnas y pizzas.',
    price: 14200,
    categoryId: 'cat_lacteos_huevos',
    stock: 28,
    unit: 'Paquete 400g',
    imageUrl: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=600&q=80',
    isFeatured: false,
    barcode: '770123456006',
    brand: 'Colanta',
    taxRateId: 'tax_iva_reducido',
  },
  {
    id: 'prod_huevos_campesinos',
    name: 'Huevos Rojos Tipo AA x30',
    description: 'Huevos frescos de gallinas libres de jaula, tamaño extra grande.',
    price: 18900,
    originalPrice: 21000,
    categoryId: 'cat_lacteos_huevos',
    stock: 50,
    unit: 'Cubeta 30 unid.',
    imageUrl: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=600&q=80',
    isFeatured: true,
    barcode: '770123456007',
    brand: 'Santa Reyes',
    taxRateId: 'tax_exento',
  },
  {
    id: 'prod_yogurt_griego',
    name: 'Yogurt Griego Natural Sin Azúcar',
    description: 'Yogurt cremoso con alto contenido de proteína natural y probióticos.',
    price: 12500,
    categoryId: 'cat_lacteos_huevos',
    stock: 32,
    unit: 'Tarro 500g',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=600&q=80',
    isFeatured: false,
    barcode: '770123456008',
    brand: 'San Martin',
    taxRateId: 'tax_iva_reducido',
  },

  // Carnes y Aves
  {
    id: 'prod_pechuga_pollo',
    name: 'Pechuga de Pollo Deshuesada',
    description: 'Pechuga fresca limpia sin piel, tierna y lista para preparar.',
    price: 16800,
    originalPrice: 19500,
    categoryId: 'cat_carnes_pescados',
    stock: 25,
    unit: 'Bandeja 1kg',
    imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=600&q=80',
    isFeatured: true,
    barcode: '770123456009',
    brand: 'Bucanero',
    taxRateId: 'tax_exento',
  },
  {
    id: 'prod_lomo_res',
    name: 'Lomo Fino de Res Premium',
    description: 'Corte magro y jugoso, ideal para asados y medallones al vino.',
    price: 38900,
    categoryId: 'cat_carnes_pescados',
    stock: 18,
    unit: 'Porción 800g',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    isFeatured: true,
    barcode: '770123456010',
    brand: 'D2 Carnicería',
    taxRateId: 'tax_exento',
  },
  {
    id: 'prod_salmon_noruego',
    name: 'Filete de Salmón del Atlántico',
    description: 'Salmón fresco congelado individualmente, rico en Omega-3.',
    price: 34500,
    originalPrice: 39000,
    categoryId: 'cat_carnes_pescados',
    stock: 20,
    unit: 'Bandeja 500g',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
    isFeatured: false,
    barcode: '770123456011',
    brand: 'Ocean Fresh',
    taxRateId: 'tax_iva_reducido',
  },

  // Panadería y Café
  {
    id: 'prod_pan_artesanal',
    name: 'Pan Masa Madre Rústico',
    description: 'Pan artesanal fermentado por 24h, corteza crocante y miga suave.',
    price: 9500,
    categoryId: 'cat_panaderia',
    stock: 22,
    unit: 'Hogaza 600g',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    isFeatured: true,
    barcode: '770123456012',
    brand: 'D2 Panadería',
    taxRateId: 'tax_iva_reducido',
  },
  {
    id: 'prod_cafe_especial',
    name: 'Café Colombiano Excelso Molido',
    description: 'Café 100% Arábica de altura con notas achocolatadas y florales.',
    price: 22800,
    originalPrice: 26000,
    categoryId: 'cat_panaderia',
    stock: 40,
    unit: 'Bolsa 500g',
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=600&q=80',
    isFeatured: true,
    barcode: '770123456013',
    brand: 'Juan Valdez',
    taxRateId: 'tax_iva_reducido',
  },

  // Despensa y Granos
  {
    id: 'prod_aceite_oliva',
    name: 'Aceite de Oliva Extra Virgen Español',
    description: 'Prensado en frío de aceitunas seleccionadas con acidez menor a 0.5%.',
    price: 36900,
    originalPrice: 42000,
    categoryId: 'cat_despensa',
    stock: 30,
    unit: 'Botella 750ml',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    isFeatured: true,
    barcode: '770123456014',
    brand: 'Carbonell',
    taxRateId: 'tax_iva_general',
  },
  {
    id: 'prod_arroz_premium',
    name: 'Arroz Flor Huila Grano Entero',
    description: 'Arroz selecto blanco de alta cocción y rendimiento en grano.',
    price: 19500,
    categoryId: 'cat_despensa',
    stock: 65,
    unit: 'Bolsa 5kg',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
    isFeatured: false,
    barcode: '770123456015',
    brand: 'Florhuila',
    taxRateId: 'tax_exento',
  },
  {
    id: 'prod_pasta_italiana',
    name: 'Pasta Spaghetti de Trigo Duro',
    description: 'Tradicional pasta italiana al dente elaborada con sémola de trigo.',
    price: 6200,
    categoryId: 'cat_despensa',
    stock: 55,
    unit: 'Paquete 500g',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281734?auto=format&fit=crop&w=600&q=80',
    isFeatured: false,
    barcode: '770123456016',
    brand: 'Barilla',
    taxRateId: 'tax_iva_reducido',
  },

  // Bebidas y Jugos
  {
    id: 'prod_jugo_naranja',
    name: 'Jugo de Naranja 100% Natural Sin Azúcar',
    description: 'Zumo recién exprimido sin preservantes ni colorantes artificiales.',
    price: 11900,
    categoryId: 'cat_bebidas',
    stock: 36,
    unit: 'Botella 1.5L',
    imageUrl: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80',
    isFeatured: false,
    barcode: '770123456017',
    brand: 'Frutto',
    taxRateId: 'tax_iva_general',
  },
  {
    id: 'prod_agua_manantial',
    name: 'Agua de Manantial con Gas',
    description: 'Agua pura mineral gasificada naturalmente desde los Andes.',
    price: 4500,
    categoryId: 'cat_bebidas',
    stock: 80,
    unit: 'Botella 1.25L',
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=600&q=80',
    isFeatured: false,
    barcode: '770123456018',
    brand: 'San Pellegrino',
    taxRateId: 'tax_iva_general',
  },

  // Aseo y Cuidado del Hogar
  {
    id: 'prod_detergente_liquido',
    name: 'Detergente Líquido Concentrado Floral',
    description: 'Máxima remoción de manchas con fórmula biodegradable y aroma duradero.',
    price: 32900,
    originalPrice: 38500,
    categoryId: 'cat_aseo_hogar',
    stock: 24,
    unit: 'Galón 3.8L',
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
    isFeatured: true,
    barcode: '770123456019',
    brand: 'Ariel',
    taxRateId: 'tax_iva_general',
  },
  {
    id: 'prod_papel_higienico',
    name: 'Papel Higiénico Triple Hoja Suavidad',
    description: 'Papel higiénico acolchado ultra absorbente x 12 rollos dobles.',
    price: 26500,
    categoryId: 'cat_aseo_hogar',
    stock: 42,
    unit: 'Paquete 12 rollos',
    imageUrl: 'https://images.unsplash.com/photo-1584556812952-905ffd0c611a?auto=format&fit=crop&w=600&q=80',
    isFeatured: false,
    barcode: '770123456020',
    brand: 'Familia',
    taxRateId: 'tax_iva_general',
  },

  // Snacks y Dulces
  {
    id: 'prod_chocolate_artesanal',
    name: 'Chocolate Oscuro 70% Cacao con Almendras',
    description: 'Barra de chocolate fino de aroma con trozos de almendra tostada.',
    price: 13500,
    categoryId: 'cat_snacks',
    stock: 45,
    unit: 'Barra 100g',
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=600&q=80',
    isFeatured: false,
    barcode: '770123456021',
    brand: 'Lok Foods',
    taxRateId: 'tax_iva_general',
  },
  {
    id: 'prod_mix_frutos_secos',
    name: 'Mix de Frutos Secos y Arándanos',
    description: 'Mezcla energética con nueces, almendras, marañones y uvas pasas.',
    price: 18200,
    originalPrice: 21500,
    categoryId: 'cat_snacks',
    stock: 38,
    unit: 'Doypack 350g',
    imageUrl: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&w=600&q=80',
    isFeatured: true,
    barcode: '770123456022',
    brand: 'D2 Saludable',
    taxRateId: 'tax_iva_reducido',
  }
];

export const DEMO_USERS: User[] = [
  {
    id: 'usr_admin_hernando',
    email: 'herminsondelgado6@gmail.com',
    name: 'Herminson Delgado (Admin)',
    role: 'admin',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    phone: '+57 300 000 0000',
    address: 'Sede Principal D2',
    createdAt: '2026-01-01T00:00:00.000Z',
    isActive: true,
  },
  {
    id: 'usr_admin_d2',
    email: 'admin@d2supermercado.com',
    name: 'Carlos Mendoza (Gerente Admin D2)',
    role: 'admin',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    phone: '+57 310 987 6543',
    address: 'Sede Central D2 - Calle 85 # 15-20, Bogotá',
    createdAt: '2026-01-10T08:00:00.000Z',
    isActive: true,
  },
  {
    id: 'usr_cliente_d2',
    email: 'cliente@d2supermercado.com',
    name: 'Mariana Gómez',
    role: 'cliente',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    phone: '+57 320 456 7890',
    address: 'Carrera 7 # 120-45, Apto 502, Bogotá',
    createdAt: '2026-02-15T14:30:00.000Z',
    isActive: true,
  }
];
